### PR TITLE
Regression tests for Expr JSON encoding

### LINKED ISSUE #72: JSON reading regression tests
Need tests that save a bunch of `StoreExpressions` as JSON and then read them to check things aren't broken.

### PR DESCRIPTION
**Pull request by danieljharvey**
Resolves #72 to ensure we don't regress Expr shape and so can't read old Exprs anymore.

### CODE REVIEW

File: test/Test/Repl.hs [hunk 1]
```diff
@@ -47,26 +56,6 @@ toEmptyAnn = toEmptyAnnotation
...
-      if toEmptyAnn expr1 /= toEmptyAnn expr2
-        then
-          Left
-            ( ">>>" <> T.pack (show expr1)
-                <> "<<< does not match >>>"
-                <> T.pack (show expr2)
-                <> "<<< "
-                <> prettyPrint expr1
-                <> " vs "
-                <> prettyPrint expr2
```
Comment (danieljharvey) [inline test/Test/Repl.hs:66]: Moved to Serialisations tests
